// The restaurant's menu, transcribed from the printed takeout menu (photos from 2026-10-09).
// Prices on the printed menu are out of date; update them here or in the menu editor.
//
// Each row is [code, Chinese name, English name, price(s), extras].
// A single number is a single price. An array lines up with the category's `sizes`;
// null means that size is not sold. `choices` lists the protein (or style) the cashier
// must pick, for "X or Y" dishes.

export type MenuRow = [
  code: string,
  altName: string,
  name: string,
  prices: number | (number | null)[],
  extras?: { spicy?: boolean; choices?: string[]; sizes?: string[] },
];

export interface MenuSection {
  name: string;
  note?: string;
  sizes?: string[];
  rows: MenuRow[];
}

const S = { spicy: true };
const PORK_CHICKEN = ["Roast Pork", "Chicken"];
const CHICKEN_PORK = ["Chicken", "Roast Pork"];
const SHRIMP_BEEF = ["Shrimp", "Beef"];
const PT_QT = ["Pt", "Qt"];

export const MENU: MenuSection[] = [
  {
    name: "Lunch Special",
    note: "Mon–Sat 11:00 am–3:30 pm. Served with vegetable fried rice and egg roll.",
    rows: [
      ["L1", "叉或雞炒麵", "Roast Pork or Chicken Chow Mein", 6.05, { choices: PORK_CHICKEN }],
      ["L2", "叉或雞撈麵", "Roast Pork or Chicken Lo Mein", 6.05, { choices: PORK_CHICKEN }],
      ["L3", "叉或雞芥蘭", "Roast Pork or Chicken w. Broccoli", 6.05, { choices: PORK_CHICKEN }],
      ["L4", "腰果雞", "Chicken w. Cashew Nuts", 6.05],
      ["L5", "魚香雞", "Chicken w. Garlic Sauce", 6.35, S],
      ["L6", "左宗雞", "General Tso's Chicken", 6.35, S],
      ["L7", "芝麻雞", "Sesame Chicken", 6.35],
      ["L8", "甜酸肉或雞", "Sweet & Sour Pork or Chicken", 6.05, { choices: ["Pork", "Chicken"] }],
      ["L9", "蘑菇雞片", "Moo Goo Gai Pan", 6.05],
      ["L10", "四川雞", "Szechuan Chicken", 6.35, S],
      ["L11", "宮保雞", "Kung Po Chicken and Peanuts", 6.35, S],
      ["L12", "湖南雞", "Hunan Chicken", 6.35, S],
      ["L13", "叉或雞蓉蛋", "Roast Pork or Chicken Egg Foo Young", 6.05, { choices: PORK_CHICKEN }],
      ["L14", "什菜牛或雞", "Beef or Chicken w. Mixed Vegetables", 6.35, { choices: ["Beef", "Chicken"] }],
      ["L15", "咖喱雞或牛", "Curry Chicken or Beef", 6.35, { spicy: true, choices: ["Chicken", "Beef"] }],
      ["L16", "無骨排", "Boneless Ribs", 7.05],
      ["L17", "芥蘭牛", "Beef w. Broccoli", 6.35],
      ["L18", "青椒牛", "Pepper Steak w. Onions", 6.35],
      ["L19", "魚香牛", "Beef w. Garlic Sauce", 6.35, S],
      ["L20", "蝦或牛炒麵", "Shrimp or Beef Chow Mein", 6.35, { choices: SHRIMP_BEEF }],
      ["L21", "蝦或牛撈麵", "Shrimp or Beef Lo Mein", 6.35, { choices: SHRIMP_BEEF }],
      ["L22", "芥蘭蝦", "Shrimp w. Broccoli", 6.7],
      ["L23", "腰果蝦", "Shrimp w. Cashew Nuts", 6.7],
      ["L24", "四川蝦", "Szechuan Shrimp", 6.7, S],
      ["L25", "宮保蝦", "Kung Po Shrimp and Peanuts", 6.7, S],
      ["L26", "蝦龍糊", "Shrimp w. Lobster Sauce", 6.7],
      ["L27", "干燒蝦", "Hot & Spicy Shrimp", 6.7, S],
      ["L28", "魚香蝦", "Shrimp w. Garlic Sauce", 6.7, S],
      ["L29", "魚香芥蘭", "Broccoli w. Garlic Sauce", 6.05, S],
      ["L30", "素什菜", "Mixed Vegetables", 6.05],
    ],
  },
  {
    name: "American Selections",
    sizes: ["Plain", "w. Fries or Fried Rice", "w. Chicken or Pork Fried Rice", "w. Shrimp or Beef Fried Rice"],
    rows: [
      ["A1", "炸雞翼", "Fried Chicken Wings (4 pcs)", [5.3, 6.6, 6.9, 7.4]],
      ["A2", "蜂蜜芥末雞翼", "Honey Mustard Wing", [5.8, 7.1, 7.4, 7.9]],
      ["A3", "炸海鮮大會", "Fried Seafood Combination", [5.8, 7.1, 7.4, 7.9]],
      ["A4", "蜜汁雞翼", "Chop Chicken Wings in Honey Sauce", [5.8, 7.1, 7.4, 7.9]],
      [
        "A5",
        "炸排骨尾",
        "Fried Spare Rib Tips",
        [5.6, 8.3, 6.9, 7.2, 7.7],
        { sizes: ["Plain Pt", "Plain Qt", "w. Fries or Fried Rice", "w. Chicken or Pork Fried Rice", "w. Shrimp or Beef Fried Rice"] },
      ],
      ["A6", "雞金手指", "Chicken Fingers", [5.15, 6.0, 6.35, 6.85]],
      ["A7", "炸小蝦", "Fried Shrimps (12 pcs)", [5.6, 6.9, 7.2, 7.7]],
      ["A8", "辣雞翅", "Hot Wing", [5.8, 7.1, 7.4, 7.9], S],
      ["A9", "炸干貝", "Fried Scallops (10 pcs)", [5.4, 6.1, 6.6, 7.1]],
      ["A10", "雞串", "Chicken on Stick", [5.6, 6.9, 7.2, 7.7]],
      ["A12", "炸蟹條", "Fried Crab Meat Sticks (4 pcs)", [5.4, 6.1, 6.6, 7.1]],
    ],
  },
  {
    name: "Appetizers",
    rows: [
      ["1", "春卷", "Pork Egg Roll", 1.4],
      ["2", "蝦春卷", "Shrimp Egg Roll", 1.5],
      ["3", "蟹角", "Crab Rangoon (10)", 5.45],
      ["4", "上海卷", "Spring Roll", 1.5],
      ["5", "鍋貼或水餃", "Dumplings (8)", 5.75, { choices: ["Fried", "Steamed"] }],
      ["6", "炸雲吞", "Fried Wontons (12) w. Sweet & Sour Sauce", 3.9],
      ["7", "炸薯條", "French Fries", 3.1],
      ["8", "無骨排", "Boneless Spare Ribs", [6.8, 10.1], { sizes: ["S", "L"] }],
      ["9", "炸包", "Donuts", 4.0],
    ],
  },
  {
    name: "Soup",
    note: "With dry noodles.",
    sizes: PT_QT,
    rows: [
      ["10", "雲吞湯", "Wonton Soup", [2.85, 4.0]],
      ["11", "蛋花湯", "Egg Drop Soup", [2.7, 3.7]],
      ["12", "蛋花雲吞湯", "Wonton Egg Drop Mix Soup", [3.05, 4.7]],
      ["13", "雞麵或飯湯", "Chicken Noodle or Rice Soup", [3.05, 4.7], { choices: ["Noodle", "Rice"] }],
      ["14", "素菜湯", "Vegetable Soup", [3.05, 4.7]],
      ["15", "酸辣湯", "Hot & Sour Soup", [3.65, 5.4], S],
      ["16", "海鮮豆腐湯", "Seafood w. Bean Curd Soup", 7.3],
      ["17", "叉或雞麵湯", "Roast Pork or Chicken Yat Gaw Mein", 5.7, { choices: PORK_CHICKEN }],
      ["18", "本樓雲吞湯", "House Special Wonton Soup", [5.2, 7.2]],
    ],
  },
  {
    name: "Fried Rice",
    sizes: PT_QT,
    rows: [
      ["19", "雞或叉炒飯", "Chicken or Roast Pork Fried Rice", [4.95, 7.6], { choices: CHICKEN_PORK }],
      ["20", "蝦或牛炒飯", "Shrimp or Beef Fried Rice", [5.3, 8.1], { choices: SHRIMP_BEEF }],
      ["21", "素菜炒飯", "Vegetable Fried Rice", [4.95, 7.6]],
      ["22", "揚州炒飯", "Young Chow Fried Rice", [5.8, 8.3]],
      ["23", "本樓炒飯", "House Special Fried Rice", [5.7, 8.3]],
    ],
  },
  {
    name: "Lo Mein",
    note: "Soft noodles.",
    sizes: PT_QT,
    rows: [
      ["24", "雞或叉撈麵", "Chicken or Roast Pork Lo Mein", [5.65, 7.8], { choices: CHICKEN_PORK }],
      ["25", "牛或蝦撈麵", "Beef or Shrimp Lo Mein", [6.05, 8.6], { choices: ["Beef", "Shrimp"] }],
      ["26", "素菜撈麵", "Vegetable Lo Mein", [5.65, 7.8]],
      ["27", "本樓撈麵", "House Special Lo Mein", [6.3, 8.8]],
    ],
  },
  {
    name: "Chow Mein",
    note: "With white rice and dry noodles.",
    sizes: PT_QT,
    rows: [
      ["28", "雞或叉炒麵", "Chicken or Roast Pork Chow Mein", [5.1, 7.4], { choices: CHICKEN_PORK }],
      ["29", "蝦或牛炒麵", "Shrimp or Beef Chow Mein", [5.3, 8.1], { choices: SHRIMP_BEEF }],
      ["30", "素菜炒麵", "Mixed Vegetables Chow Mein", [5.1, 7.4]],
      ["31", "本樓炒麵", "House Special Chow Mein", [5.8, 8.8]],
    ],
  },
  {
    name: "Chicken",
    note: "With white rice.",
    sizes: PT_QT,
    rows: [
      ["32", "腰果雞", "Chicken w. Cashew Nuts", [5.85, 8.65]],
      ["33", "芥蘭雞", "Chicken w. Broccoli", [5.85, 8.65]],
      ["34", "雪豆雞", "Chicken w. Snow Peas", [5.85, 8.65]],
      ["35", "什錦雞", "Chicken w. Mixed Vegetables", [5.85, 8.65]],
      ["36", "咖喱雞", "Curry Chicken", [5.85, 8.65], S],
      ["37", "豆腐雞", "Chicken w. Bean Curd", [5.85, 8.65]],
      ["38", "蘑菇雞", "Chicken w. Mushrooms", [5.85, 8.65]],
      ["39", "玉米雞", "Chicken w. Baby Corn", [5.85, 8.65]],
      ["40", "青椒雞", "Chicken w. Pepper & Onion", [5.85, 8.65]],
      ["41", "蘑菇雞片", "Moo Goo Gai Pan", [5.85, 8.65]],
    ],
  },
  {
    name: "Beef",
    note: "With white rice.",
    sizes: PT_QT,
    rows: [
      ["42", "什錦牛", "Beef w. Mixed Vegetables", [6.2, 9.2]],
      ["43", "芥蘭牛", "Beef w. Broccoli", [6.2, 9.2]],
      ["44", "青椒牛", "Pepper Steak w. Onion", [6.2, 9.2]],
      ["45", "雪豆牛", "Beef w. Snow Peas", [6.2, 9.2]],
      ["46", "蠔油牛", "Beef w. Oyster Sauce", [6.2, 9.2]],
      ["47", "豆腐牛", "Beef w. Bean Curd", [6.2, 9.2]],
      ["48", "蘑菇牛", "Beef w. Mushrooms", [6.2, 9.2]],
      ["49", "咖喱牛", "Curry Beef w. Onion", [6.2, 9.2], S],
    ],
  },
  {
    name: "Seafood",
    note: "With white rice.",
    sizes: PT_QT,
    rows: [
      ["50", "腰果蝦", "Shrimp w. Cashew Nuts", [6.55, 10.45]],
      ["51", "什錦蝦", "Shrimp w. Mixed Vegetables", [6.55, 10.45]],
      ["52", "芥蘭蝦", "Shrimp w. Broccoli", [6.55, 10.45]],
      ["53", "雪豆蝦", "Shrimp w. Snow Peas", [6.55, 10.45]],
      ["54", "咖喱蝦", "Curry Shrimp w. Onion", [6.55, 10.45], S],
      ["55", "蝦龍糊", "Shrimp w. Lobster Sauce", [6.55, 10.45]],
      ["56", "蘑菇蝦", "Shrimp w. Mushrooms", [6.55, 10.45]],
      ["57", "蠔油蝦", "Shrimp w. Oyster Sauce", [6.55, 10.45]],
      ["58", "玉米蝦", "Shrimp w. Baby Corn", [6.55, 10.45]],
      ["59", "豆腐蝦", "Shrimp w. Bean Curd", [6.55, 10.45]],
    ],
  },
  {
    name: "Pork",
    note: "With white rice.",
    sizes: PT_QT,
    rows: [
      ["60", "什錦叉燒", "Roast Pork w. Mixed Vegetables", [5.6, 8.35]],
      ["61", "芥蘭叉燒", "Roast Pork w. Broccoli", [5.6, 8.35]],
      ["62", "腰果叉燒", "Roast Pork w. Cashew Nuts", [5.6, 8.35]],
      ["63", "雪豆叉燒", "Roast Pork w. Snow Peas", [5.6, 8.35]],
      ["64", "蘑菇叉燒", "Roast Pork w. Mushrooms", [5.6, 8.35]],
      ["65", "蠔油叉燒", "Roast Pork w. Oyster Sauce", [5.6, 8.35]],
      ["66", "玉米叉燒", "Roast Pork w. Baby Corn", [5.6, 8.35]],
    ],
  },
  {
    name: "Chop Suey",
    note: "With white rice.",
    sizes: PT_QT,
    rows: [
      ["67", "雞或叉什碎", "Chicken or Roast Pork Chop Suey", [5.4, 7.8], { choices: CHICKEN_PORK }],
      ["68", "蝦或牛什碎", "Shrimp or Beef Chop Suey", [5.55, 8.3], { choices: SHRIMP_BEEF }],
      ["69", "素菜什碎", "Vegetable Chop Suey", [5.4, 7.8]],
      ["70", "本樓什碎", "House Special Chop Suey", [5.8, 8.8]],
    ],
  },
  {
    name: "Sweet & Sour",
    note: "With white rice.",
    sizes: PT_QT,
    rows: [
      ["71", "甜酸肉", "Sweet & Sour Pork", [5.85, 8.65]],
      ["72", "甜酸雞", "Sweet & Sour Chicken", [5.85, 8.65]],
    ],
  },
  {
    name: "Chow Mei Fun",
    rows: [
      ["73", "叉或雞炒米", "Roast Pork or Chicken Chow Mei Fun", 7.55, { choices: PORK_CHICKEN }],
      ["74", "蝦或牛炒米", "Shrimp or Beef Chow Mei Fun", 7.75, { choices: SHRIMP_BEEF }],
      ["75", "素菜炒米", "Vegetable Chow Mei Fun", 7.55],
      ["76", "星州炒米", "Singapore Chow Mei Fun", 7.75, S],
      ["77", "本樓炒米", "House Special Chow Mei Fun", 7.75],
    ],
  },
  {
    name: "Egg Foo Young",
    note: "With white rice. 3 pancakes per order.",
    rows: [
      ["78", "什錦蓉蛋", "Mixed Vegetables Egg Foo Young", 7.3],
      ["79", "叉燒蓉蛋", "Roast Pork Egg Foo Young", 7.3],
      ["80", "雞蓉蛋", "Chicken Egg Foo Young", 7.3],
      ["81", "牛蓉蛋", "Beef Egg Foo Young", 7.75],
      ["82", "蝦蓉蛋", "Shrimp Egg Foo Young", 7.75],
      ["83", "本樓蓉蛋", "House Special Egg Foo Young", 8.5],
    ],
  },
  {
    name: "Vegetable",
    note: "With white rice.",
    rows: [
      ["84", "魚香芥蘭", "Broccoli w. Garlic Sauce", 7.75, S],
      ["85", "魚香炸豆腐", "Fried Bean Curd w. Garlic Sauce", 7.75, S],
      ["86", "素什錦", "Mixed Vegetables", 7.75],
      ["87", "清炒芥蘭", "Broccoli w. Brown Sauce", 7.75],
      ["88", "四川豆腐", "Bean Curd, Szechuan Style", 7.75, S],
      ["89", "家常豆腐", "Bean Curd Home Style", 7.75],
    ],
  },
  {
    name: "Combination Plates",
    note: "Served with vegetable fried rice and egg roll.",
    rows: [
      ["C1", "雞炒麵", "Chicken Chow Mein", 7.65],
      ["C2", "魚香雞", "Chicken w. Garlic Sauce", 8.2, S],
      ["C3", "芥蘭肉或雞", "Pork or Chicken w. Broccoli", 7.65, { choices: ["Pork", "Chicken"] }],
      ["C4", "左宗雞", "General Tso's Chicken", 8.4, S],
      ["C5", "芝麻雞", "Sesame Chicken", 8.4],
      ["C6", "四川雞", "Szechuan Chicken", 8.2, S],
      ["C7", "甜酸雞或肉", "Sweet & Sour Chicken or Pork", 7.65, { choices: ["Chicken", "Pork"] }],
      ["C8", "肉或雞撈麵", "Pork or Chicken Lo Mein", 7.65, { choices: ["Pork", "Chicken"] }],
      ["C9", "湖南雞", "Hunan Chicken", 8.2, S],
      ["C10", "腰果雞", "Chicken w. Cashew Nuts", 7.65],
      ["C11", "無骨排", "Boneless Spare Ribs", 8.4],
      ["C12", "干燒蝦", "Hot & Spicy Shrimp", 8.4, S],
      ["C13", "蝦龍糊", "Shrimp w. Lobster Sauce", 8.4],
      ["C14", "芥蘭蝦或牛", "Shrimp or Beef w. Broccoli", 8.4, { choices: SHRIMP_BEEF }],
      ["C15", "青椒牛", "Pepper Steak w. Onion", 8.4],
      ["C16", "四川牛", "Szechuan Beef", 8.2, S],
      ["C17", "干燒牛", "Hot & Spicy Beef", 8.2, S],
      ["C18", "蘑菇雞片", "Moo Goo Gai Pan", 7.65],
      ["C19", "叉或雞蓉蛋", "Pork or Chicken Egg Foo Young", 7.65, { choices: ["Pork", "Chicken"] }],
    ],
  },
  {
    name: "Diet Dishes",
    note: "Steamed, with white rice.",
    sizes: PT_QT,
    rows: [
      ["D1", "蒸什菜", "Steamed Mixed Vegetables", [5.3, 7.75]],
      ["D2", "蒸什菜雞", "Steamed Chicken w. Mixed Vegetables", [5.75, 8.55]],
      ["D3", "蒸芥蘭雞", "Steamed Chicken w. Broccoli", [5.75, 8.55]],
      ["D4", "蒸芥蘭蝦", "Steamed Shrimp w. Broccoli", [6.4, 10.45]],
    ],
  },
  {
    name: "House Special",
    note: "With white rice.",
    rows: [
      ["H1", "四川雞", "Szechuan Chicken", 9.55, S],
      ["H2", "魚香雞", "Chicken w. Garlic Sauce", 9.55, S],
      ["H3", "宮保雞", "Kung Pao Chicken", 9.55, S],
      ["H4", "芝麻雞", "Sesame Chicken", 10.1],
      ["H5", "左宗雞", "General Tso's Chicken", 10.1, S],
      ["H6", "泰國雞", "Panang Chicken", 10.1],
      ["H7", "陳皮雞", "Orange Flavored Chicken", 10.1, S],
      ["H8", "檸檬雞", "Lemon Chicken", 9.1],
      ["H9", "湖南雞", "Hunan Chicken", 9.55, S],
      ["H10", "菠蘿雞", "Pineapple Chicken", 9.55],
      ["H11", "干燒牛肉絲", "Hot & Spicy Shredded Beef", 10.1, S],
      ["H12", "龍鳳配", "Dragon & Phoenix", 10.6],
      ["H13", "四川牛", "Szechuan Beef", 10.1, S],
      ["H14", "蒙古牛", "Mongolian Beef", 10.35],
      ["H15", "湖南牛", "Hunan Beef", 10.1, S],
      ["H16", "魚香牛", "Beef w. Garlic Sauce", 10.1, S],
      ["H17", "魚香兩樣", "Double Delight w. Garlic Sauce", 10.2, S],
      ["H18", "魚香干貝", "Scallop w. Garlic Sauce", 11.6, S],
      ["H19", "炒三樣", "Triple Delight", 10.0],
      ["H20", "海鮮大會", "Seafood Delight", 12.65],
      ["H21", "全家福", "Happy Family", 12.65],
      ["H22", "炒四季", "Four Seasons", 10.7],
      ["H23", "魚香蝦", "Shrimp w. Garlic Sauce", 11.85, S],
      ["H24", "干燒蝦", "Hot & Spicy Shrimp", 11.1, S],
      ["H25", "魚香雙鮮", "Shrimp & Scallops w. Garlic Sauce", 11.85, S],
      ["H26", "湖南蝦", "Hunan Shrimp", 11.85, S],
      ["H27", "爆雙丁", "Chicken & Shrimp", 9.1],
    ],
  },
  {
    name: "Side Orders",
    rows: [
      ["", "白飯", "White Rice", [2.75, 3.75], { sizes: PT_QT }],
      ["", "麵干", "Dry Noodles", 0.75],
    ],
  },
];
